name: Main Pipe Line

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Stage 0. PRECONDITIONS. Download all the 3rd party packages using NPM I command
      run: npm i
    - name: Stage 1. Testing Main Pages and Their Base Functionality
      run: npm run mpe
    - name: Stage 2. Smoke Tests (Happy Path) for all the pages
      run: npm run smokePositive
    - name: Stage 3. Smoke Tests (Negative) for all the pages
      run: npm run smokeNegative
